[project]
name = "sriaas_role_permissions"
description = "Configurable role permission helpers for SRIAAS Frappe apps."
authors = [
    { name = "SRIAAS", email = "webdevelopersriaas@gmail.com"}
]

requires-python = ">=3.14,<3.15"
readme = "README.md"
dynamic = ["version"]

dependencies = [
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# Frappe compatibility requirement
[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
crm = ">=1.81.0,<2.0.0"

[tool.ruff]
target-version = "py314"
